### ISSUE TITLE
cuBLAS を追加することはできますか?

### ISSUE THREAD

**Issue by haradatm** [icoxfog417/datascience-template#1]
素晴らしい! environment-colab.yml ありがとうございます. Colab の Notebook を引っ越したいのですが cuBLAS がないようです. cuBLAS を追加することはできますか?

**Comment by icoxfog417** [comment]
ご利用いただきありがとうございます！引っ越しのお役に立てば幸いです。多分cudatoolkitがないせいだと思うのですが、これはお手元のGPUに合わせてインストールする必要がありそうです。`nvcc --version`でCUDAのバージョンが確認できるので、該当するバージョンの[`cudatoolkit`](https://anaconda.org/nvidia/cudatoolkit)を入れればcuBLASも入ると思います。(以下は、SageMaker Studio Labでのnvcc --version`実行結果です。この場合11.2ですね)。

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
```

**Comment by haradatm** [comment]
早速の reply ありがとうございます. そもそも environment-colab.yml は GPU 前提ではなかったのですね. 大変失礼しました. ちなみに, cudatoolkit は入れていますが, clab に比べ cuda 系の開発リソースが足りず(おそらく自力では置けない?), 所望の公開コードのビルドに失敗します. 以下は, CUDALibrarySamples (https://github.com/NVIDIA/CUDALibrarySamples) のサンプルコードのビルド結果です.

> fatal error: cublas_v2.h: No such file or directory
>   54 | #include <cublas_v2.h>

自身でもう少し調べてみます. 
environment-colab.yml  の GPU 版もあると便利だなと思いました. ありがとうございました.

**Comment by icoxfog417** [comment]
GPU前提にしたいとは考えています。PyTorchは自動でスイッチしてくれたと思いますが、TensorFlowが悩みどころですね(TensorFlow GPUを入れないといけない認識です)。2つに分けるのも手間なので、もしうまい方法があれば教えていただきたいです。cudatoolkitもおそらくGPUがなければないで邪魔しないと思うので入れることはできると思います。

ビルドする際、condaで作成した環境をactivateしているでしょうか? cudatoolkitが入っているにもかかわらずcublasがないと言われるのは少しおかしいので、その点が気になりました。

**Comment by haradatm** [comment]
repy ありがとうございます! 

> condaで作成した環境をactivateしているでしょうか?
これについては Yes です.

私の問題は, Colab に比べ  Studio Lab の方は cuda 系の dev パッケージが足りないことのようです. 

- Colab

> apt list --installed | grep cublas
cuda-cublas-10-0/unknown,now 10.0.130-1 amd64 [installed,automatic]
cuda-cublas-dev-10-0/unknown,now 10.0.130-1 amd64 [installed,automatic]
libcublas-11-0/unknown,now 11.2.0.252-1 amd64 [installed]
libcublas-11-1/unknown,now 11.3.0.106-1 amd64 [installed]
libcublas-dev/unknown,now 10.2.1.243-1 amd64 [installed,upgradable to: 10.2.3.254-1]
libcublas-dev-11-0/unknown,now 11.2.0.252-1 amd64 [installed,automatic]
libcublas-dev-11-1/unknown,now 11.3.0.106-1 amd64 [installed]
libcublas10/unknown,now 10.2.1.243-1 amd64 [installed,upgradable to: 10.2.3.254-1]

- Studio Lab

> apt list --installed | grep cublas
libcublas-11-2/now 11.4.1.1043-1 amd64 [installed,local]

root 権限がないので, どうにか conda のビルド済みで置き換えるように手を加えて行かないと突破は難しそうですね.
問題の本質は environment-colab.yml ではなく Studio Lab 上でのビルド方法のようです.
ありがとうございました.

**Comment by haradatm** [comment]
repy ありがとうございます!

> condaで作成した環境をactivateしているでしょうか?
これについては Yes です.

私の問題は, Colab に比べ Studio Lab の方は cuda 系の dev パッケージが足りないことのようです.

- Colab

> apt list --installed | grep cublas
> cuda-cublas-10-0/unknown,now 10.0.130-1 amd64 [installed,automatic]
> cuda-cublas-dev-10-0/unknown,now 10.0.130-1 amd64 [installed,automatic]
> libcublas-11-0/unknown,now 11.2.0.252-1 amd64 [installed]
> libcublas-11-1/unknown,now 11.3.0.106-1 amd64 [installed]
> libcublas-dev/unknown,now 10.2.1.243-1 amd64 [installed,upgradable to: 10.2.3.254-1]
> libcublas-dev-11-0/unknown,now 11.2.0.252-1 amd64 [installed,automatic]
> libcublas-dev-11-1/unknown,now 11.3.0.106-1 amd64 [installed]
> libcublas10/unknown,now 10.2.1.243-1 amd64 [installed,upgradable to: 10.2.3.254-1]

- Studio Lab

> apt list --installed | grep cublas
> libcublas-11-2/now 11.4.1.1043-1 amd64 [installed,local]

root 権限がないので, どうにか conda のビルド済みで置き換えるように手を加えて行かないと突破は難しそうですね.
問題の本質は environment-colab.yml ではなく Studio Lab 上でのビルド方法のようです.
ありがとうございました.

**Comment by icoxfog417** [comment]
@haradatm さん、詳しく調査を頂きありがとうございました！ビルドをするのにDev系のライブラリが必要なんですね。いちおう、condaでcudatoolkii-devがインストールできるみたいです。こちらを使えばビルドできるかもしれません。

https://anaconda.org/conda-forge/cudatoolkit-dev

**Comment by haradatm** [comment]
@icoxfog417 さん, その手がありましたね! ありがとうございます!
`conda clean' して試していますが, cudatoolkit-dev を入れるにはディスクが足りなさそうです. 大きなヒントをいただいたので,あとは地道に頑張ってみます.

**Comment by haradatm** [comment]
@icoxfog417 その手がありますね. ありがとうございます!
ちなみに, cudatoolkii-dev を入れるには libxml2.so が必要らしいです. そのため, conda install libxml2 後に LD_LIBRARY_PATH に ~/studio-lab-user/.conda/envs/colab/lib を追加してから conda install cudatoolkii-dev で入れました. 加えて cmake を入れることで前述の CUDALibrarySamples が make できました. 引き続き, Colab からの移行を試してみます.

**Comment by icoxfog417** [comment]
@haradatm おお～上手くいってよかったです！知見を共有いただきありがとうございます。ブログ記事などにまとめていただけたらすごくうれしいです！
